### ISSUE TITLE
Hi, how can i make bmp to nii to uplaod my predict to codelab

### ISSUE THREAD

**Issue by zz10001** [LeadingIndiaAI/Liver-Tumor-Segmentation#1]

**Comment by Kathi-Kiran** [comment]
can you please help me out that what dataset you have adopted from codalab challenge as i downloaded this https://competitions.codalab.org/competitions/17094  but these are .nii files please help me as  i am new to it i am running code in google colab

**Comment by zz10001** [comment]
> can you please help me out that what dataset you have adopted from codalab challenge as i downloaded this https://competitions.codalab.org/competitions/17094 but these are .nii files please help me as i am new to it i am running code in google colab

Hi, the dataset adopted from codalab challenge actually is all .nii file like this, it all 3d dataset, you can visual it by itksnap or SimpleItk. of course, you can cut every nii(dim ``512*512*Z``) data along Z axis to png、bmp、npy etc, then use 2d unet to train a model to segment the dataset, and I recommend not train a model in Colab, because the I/O in colab is too slow compare with train it on your own server.
![image](https://user-images.githubusercontent.com/39954774/103479591-c0b9b400-4e09-11eb-94f1-dabae4ca5cca.png)

**Comment by Kathi-Kiran** [comment]
which dataset you have used for your work on this project?

**Comment by zz10001** [comment]
> which dataset you have used for your work on this project?

Sorry, I don't use this project to train, the dataset I used is LITS2017 from [codalab](https://competitions.codalab.org/competitions/17094), maybe you can according to this [repo](https://github.com/assassint2017/MICCAI-LITS2017) to start research. Best wishes
